### PR TITLE
Add the Batched VOPRF (P-384, SHA-384) variant.

### LINKED ISSUE #6: Adding additional token types.
@chris-wood Would it be reasonable to add a token type for P-384 to reflect the default VOPRF type we have in the base draft? (we also need a P-384 batched variant for PST updates to standard). If that's fine, I can send a PR for the type.

### PR DESCRIPTION
**Pull request by dvorak42**
Resolves #6.

### CODE REVIEW

**Comment by dvorak42** [comment]
@raphaelrobert @chris-wood Could one of you review (can't add reviewers for some reason).

**Review by raphaelrobert — CHANGES_REQUESTED** [review]
Thanks for the PR. I think we need to make some more changes because "ristretto255-SHA512" is hard-coded throughout the document and we need more flexibility. Let me know if you want to do that, otherwise I can follow up.

**Comment by dvorak42** [comment]
Not sure what the right way of doing it, but tried doing a pass calling out you should use the identifier (from the VOPRF document) and token_type based on the ciphersuite.

**Review by raphaelrobert — APPROVED** [review]
Thanks, I think this works. For the sake of completeness, I tried to implement this and it seems to work as expected.

**Pull request merged**
